// File: js/tailwind-config.js
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "tertiary-fixed-dim": "#86cfff",
                "primary-fixed-dim": "#ffb5a0",
                "on-primary-fixed-variant": "#862200",
                "primary": "#b02f00",
                "error": "#ba1a1a",
                "inverse-surface": "#2e3132",
                "surface-tint": "#b02f00",
                "on-primary": "#ffffff",
                "surface-container-high": "#e7e8e9",
                "on-surface": "#191c1d",
                "on-error-container": "#93000a",
                "surface-bright": "#f8f9fa",
                "secondary-fixed-dim": "#bdc2ff",
                "on-secondary-fixed": "#000767",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f3f4f5",
                "inverse-on-surface": "#f0f1f2",
                "on-secondary": "#ffffff",
                "on-background": "#191c1d",
                "error-container": "#ffdad6",
                "on-surface-variant": "#5b4039",
                "on-primary-fixed": "#3b0900",
                "primary-fixed": "#ffdbd1",
                "surface-container": "#edeeef",
                "secondary": "#4c56af",
                "outline": "#907067",
                "on-tertiary-container": "#fcfcff",
                "surface-variant": "#e1e3e4",
                "on-error": "#ffffff",
                "secondary-fixed": "#e0e0ff",
                "surface-container-highest": "#e1e3e4",
                "surface": "#f8f9fa",
                "primary-container": "#ff5722",
                "tertiary": "#00628c",
                "secondary-container": "#959efd",
                "on-tertiary-fixed-variant": "#004c6d",
                "on-secondary-container": "#27308a",
                "on-tertiary": "#ffffff",
                "on-secondary-fixed-variant": "#343d96",
                "tertiary-container": "#007caf",
                "on-primary-container": "#541200",
                "background": "#f8f9fa",
                "on-tertiary-fixed": "#001e2e",
                "tertiary-fixed": "#c8e6ff",
                "surface-dim": "#d9dadb",
                "inverse-primary": "#ffb5a0",
                "outline-variant": "#e4beb4"
            },
            fontFamily: {
                "headline": ["Epilogue"],
                "body": ["Inter"],
                "label": ["Lexend"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
}